server:
  port: 9002

spring:
  application:
    name: han-consumer-user

ribbon:
  eureka:
    enabled: false

# 项目的provider-user module 的application name
han-provider-user:
  ribbon:
    NIWSServerListClassName: com.netflix.loadbalancer.ConfigurationBasedServerList
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.WeightedResponseTimeRule

logging:
  level:
    org.springframework.cloud: debug
