server:
  port: 8011

spring:
  profiles:
    active: dev
  application:
    name: @pom.artifactId@

  data:
    elasticsearch:
      cluster-name: my-application # 与elasticsearch.yml中的cluster.name对应
      cluster-nodes: localhost:9300 # es ip
      repositories:
        enabled: true

  datasource:
    url: jdbc:mysql://localhost:3306/bboyhan?characterEncoding=UTF-8&useUnicode=true&useSSL=false
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver

